version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Wanaku related
      - dependency-name: "ai.wanaku:*"
      # Camel related
      - dependency-name: "org.apache.camel:*"
      - dependency-name: "org.apache.camel.quarkus:*"
      - dependency-name: "io.quarkus:*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
